### ISSUE TITLE
starting in local system

### ISSUE THREAD

**Issue by Ak-Srivastav** [codeterrayt/WhatsAppCabBookingBot#1]
Hi,

Is it possible for you to make a 2 mins short video on how to start and run commands.

Thanks!
Amit

**Comment by codeterrayt** [comment]
Hello @Ak-Srivastav just follow the installation guide! 
![image](https://github.com/codeterrayt/WhatsAppCabBookingBot/assets/76623307/da1293b3-9283-412e-aaa6-c886777b51a4)

**Comment by codeterrayt** [comment]
@Ak-Srivastav To connect to the database, edit the .env file to add the following key-value pairs: DB_HOST, DB_USERNAME, DB_PASSWORD, and MYSQL_DATABASE. These must correspond to the database setup on your local system. Once you have completed this step, please follow the instructions provided. I have added the .env file; kindly pull it. My main system is currently offline, so I will add the SQL file to the repository as soon as it is back online. Please be patient in the meantime.

**Comment by codeterrayt** [comment]
I have added the sql file pull it
